### ISSUE TITLE
Action generic version broken

### ISSUE THREAD

**Issue by linux4life798** [antoniovazquezblanco/setup-ghidra#67]
Using `antoniovazquezblanco/setup-ghidra@v2` in my action, as mentioned in the README.md, doesn't work.

I get the following error:
![Image](https://github.com/user-attachments/assets/afe46b47-ecf2-4ebb-b684-fae9b666968b)

I was going to update the readme to pin a specific version, but I believe this might be some tag creation issue.

**Comment by linux4life798** [comment]
I have to pin it to specifically `antoniovazquezblanco/setup-ghidra@v2.0.12`.

**Comment by linux4life798** [comment]
Thanks for making the action!

**Comment by antoniovazquezblanco** [comment]
It seems that there is no 'v2' tag but 'v2.0.0'. I've updated the readme to avoid the confusion.

Thanks for the feedback!

**Comment by Margen67** [comment]
This wasn't fixed. Actions are supposed to have a tag like this so you don't have to manually update the workflow every time there's a minor change.
